export const colorClasses = {
    amber: {
        section: "bg-amber-950",
        badge: "bg-amber-700",
        card: "bg-amber-700",
        buttonPrimary: "bg-amber-600 hover:bg-amber-700",
        buttonSecondary: "border-amber-400 hover:bg-amber-900",
    },
    blue: {
        section: "bg-blue-950",
        badge: "bg-blue-700",
        card: "bg-blue-700",
        buttonPrimary: "bg-blue-600 hover:bg-blue-700",
        buttonSecondary: "border-blue-400 hover:bg-blue-900",
    },
    cyan: {
        section: "bg-cyan-950",
        badge: "bg-cyan-700",
        card: "bg-cyan-700",
        buttonPrimary: "bg-cyan-600 hover:bg-cyan-700",
        buttonSecondary: "border-cyan-400 hover:bg-cyan-900",
    },
    emerald: {
        section: "bg-emerald-950",
        badge: "bg-emerald-700",
        card: "bg-emerald-700",
        buttonPrimary: "bg-emerald-600 hover:bg-emerald-700",
        buttonSecondary: "border-emerald-400 hover:bg-emerald-900",
    },
    green: {
        section: "bg-green-950",
        badge: "bg-green-700",
        card: "bg-green-700",
        buttonPrimary: "bg-green-600 hover:bg-green-700",
        buttonSecondary: "border-green-400 hover:bg-green-900",
    },
    indigo: {
        section: "bg-indigo-950",
        badge: "bg-indigo-700",
        card: "bg-indigo-700",
        buttonPrimary: "bg-indigo-600 hover:bg-indigo-700",
        buttonSecondary: "border-indigo-400 hover:bg-indigo-900",
    },
    lime: {
        section: "bg-lime-950",
        badge: "bg-lime-700",
        card: "bg-lime-700",
        buttonPrimary: "bg-lime-600 hover:bg-lime-700",
        buttonSecondary: "border-lime-400 hover:bg-lime-900",
    },
    orange: {
        section: "bg-orange-950",
        badge: "bg-orange-700",
        card: "bg-orange-700",
        buttonPrimary: "bg-orange-600 hover:bg-orange-700",
        buttonSecondary: "border-orange-400 hover:bg-orange-900",
    },
    red: {
        section: "bg-red-950",
        badge: "bg-red-700",
        card: "bg-red-700",
        buttonPrimary: "bg-red-600 hover:bg-red-700",
        buttonSecondary: "border-red-400 hover:bg-red-900",
    },
    rose: {
        section: "bg-rose-950",
        badge: "bg-rose-700",
        card: "bg-rose-700",
        buttonPrimary: "bg-rose-600 hover:bg-rose-700",
        buttonSecondary: "border-rose-400 hover:bg-rose-900",
    },
    yellow: {
        section: "bg-yellow-950",
        badge: "bg-yellow-700",
        card: "bg-yellow-700",
        buttonPrimary: "bg-yellow-600 hover:bg-yellow-700",
        buttonSecondary: "border-yellow-400 hover:bg-yellow-900",
    },
    transparent: {
        section: "bg-transparent",
        badge: "bg-transparent",
        card: "bg-transparent",
        buttonPrimary: "bg-transparent hover:bg-white/10",
        buttonSecondary: "border-white/30 hover:bg-white/10",
    },
    sky: {
        section: "bg-sky-950",
        badge: "bg-sky-700",
        card: "bg-sky-700",
        buttonPrimary: "bg-sky-600 hover:bg-sky-700",
        buttonSecondary: "border-sky-400 hover:bg-sky-900",
    }
} as const;